# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile is used for testing setup scripts via http.
# Requires python-apt installed

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  config.vm.provision "shell", inline: <<-SHELL
    # Setup frontend workplace
    curl -s "https://raw.githubusercontent.com/rustamkulenov/workplace/master/frontend/setup.sh" | sudo bash -s
    # Setup devops workplace
    curl -s "https://raw.githubusercontent.com/rustamkulenov/workplace/master/devops/setup.sh" | sudo bash -s
  SHELL
end
